// EvolveSWDB advisor update. Date: 2026-09-24 (Eastern Time).
import fs from 'node:fs/promises';
import path from 'node:path';
import {Presentation,PresentationFile} from '@oai/artifact-tool';
import {resolvePresentationFont,applyPresentationChartFont,finalizePresentation} from '/Users/yanrujhou/.codex/plugins/cache/openai-primary-runtime/presentations/26.909.12148/skills/presentations/container_tools/artifact_tool_utils.mjs';
const root='/Users/yanrujhou/CLionProjects/EvolveSWDB';
const work=path.join(root,'weeklogs/2026-09-24');
const build=path.join(work,'.build');
const skill='/Users/yanrujhou/.codex/plugins/cache/openai-primary-runtime/presentations/26.909.12148/skills/presentations';
const runtime='/Users/yanrujhou/.cache/codex-runtimes/codex-primary-runtime/dependencies';
const family=resolvePresentationFont();
console.log('Font:',family);
const p=Presentation.create({slideSize:{width:1280,height:720}});
const C={blue:'#00274C',maize:'#FFCB05',ice:'#E8F0F9',light:'#4A6FA5',body:'#1A1A1A',muted:'#555555',border:'#BDC3C7',alt:'#F4F4F4',white:'#FFFFFF'};
const notes=[];
function rect(s,x,y,w,h,fill){return s.shapes.add({geometry:'rect',position:{left:x,top:y,width:w,height:h},fill,line:{fill:'none',width:0}});}
function txt(s,text,x,y,w,h,size=28,bold=false,color=C.body){const a=s.shapes.add({geometry:'textbox',position:{left:x,top:y,width:w,height:h},fill:'none',line:{fill:'none',width:0}});a.text=text;a.text.style={typeface:family,fontSize:size,bold,color,autoFit:'none'};return a;}
function slide(title,narration,sources,backup=false){const s=p.slides.add();s.background.fill=C.white;rect(s,0,0,1280,102,C.blue);rect(s,0,0,10,102,C.maize);txt(s,title,46,28,1190,60,40,true,C.white);txt(s,`EvolveSWDB    2026-09-24${backup?'    Backup':''}`,46,674,1070,30,20,false,C.muted);txt(s,String(p.slides.items.length),1190,674,50,30,20,false,C.muted);const note=narration+'\n\nSources (repository snapshot a38dfac, reviewed 2026-09-24):\n'+sources.map(x=>root+'/'+x).join('\n');s.speakerNotes.textFrame.setText(note);notes.push({title,narration,sources});return s;}
function table(s,values,x,y,w,h,widths,size=25){const t=s.tables.add({rows:values.length,columns:values[0].length,left:x,top:y,width:w,height:h,columnWidths:widths,values});t.borders.assign({fill:C.border,width:1,style:'solid'});for(let r=0;r<values.length;r++){t.rows[r].height=h/values.length;for(let c=0;c<values[0].length;c++){const cell=t.getCell(r,c);cell.fill=r===0?C.blue:(r%2===0?C.alt:C.white);cell.text.style={typeface:family,fontSize:size,bold:r===0,color:r===0?C.white:C.body};}}return t;}
function bottom(s,text){rect(s,46,584,1188,64,'#FFF4CC');txt(s,text,65,597,1150,44,26,true,C.blue);}
const evidence=JSON.parse(await fs.readFile(path.join(build,'evidence.json'),'utf8'));
const profiles=Object.values(evidence.profiles).sort((a,b)=>a.input.localeCompare(b.input));
const small=profiles.find(d=>d.input.includes('g16'));
const large=profiles.find(d=>d.input.includes('g22'));
const pf=['records/profiles/gapbs-pr-jacobi.kron-g16-k16.mbit10.20260922t212416z.yaml','records/profiles/gapbs-pr-jacobi.kron-g22-k16.mbit10.20260922t215412z.yaml'];
let s=slide('Software Database: first-week progress',
`0:00–0:45 (45 seconds). ArchEvolve needs a common description of what a kernel computes, how each implementation touches memory, and what profiling measured. We have implemented that Software Database. It keeps these facts in versioned records, supports queries, and exports a workload view for the hardware side. The current application is GAPBS. We have six kernels, eight implementations and thirty-two profiles across four inputs. Thirty-one profiles are complete. This is infrastructure plus initial characterization evidence. The new strategy catalog can screen opportunities, but we have not yet measured an implementation produced by applying one of those strategies. Today I will show one example, the implemented support, and the next experiment I propose.`,
['CONTEXT.md','swdb/cli.py','swdb/view.py','.scratch/evolveswdb-2026-09-22/map.md','.scratch/optimization-strategies-2026-09-23/map.md']);
txt(s,'Purpose',48,140,300,42,30,true,C.blue);
txt(s,'Give ArchEvolve a shared record of computation,\nmemory behavior, and measured performance.',48,190,1140,90,34);
table(s,[['Implemented','Current coverage'],['Describe and query application code','6 kernels, 8 implementations'],['Profile each implementation on each input','32 profiles across 4 inputs'],['Screen optimization strategies','5 strategies, 2 intrinsics']],48,309,1184,232,[630,554],26);
bottom(s,'31 profiles complete. Strategy application and measured gains are the next step.');

s=slide('One kernel can have different memory behavior',
`0:45–1:45 (60 seconds). A kernel is identified by its computation and correctness check. An implementation is the actual code that passes that check. For PageRank, we record the upstream Gauss-Seidel and Jacobi implementations separately. The example expression is a simplified view of their recorded gather: read a neighbor identifier from an index array, then use it to read a contribution. We represent each array access as a step, so the database retains the indirection rather than only labeling the whole function irregular. Both implementations share this pattern class, but their semantics differ. Gauss-Seidel updates contributions during the sweep and has a recorded loop-carried dependency. Jacobi has a separate contribution pass and no recorded dependency for this gather. A profile then records what happens for one implementation, input and machine. That separation lets us ask useful questions without mixing code facts and measurements.`,
['docs/adr/0001-kernel-identity-is-its-correctness-check.md','docs/adr/0003-access-pattern-is-a-chain-of-steps.md','records/implementations/gapbs-pr-gs.yaml','records/implementations/gapbs-pr-jacobi.yaml']);
txt(s,'Example: PageRank reads a neighbor’s contribution',48,134,1170,46,30,true,C.blue);
rect(s,48,192,1184,90,C.alt);txt(s,'contribution[neighbor_index[e]]',75,213,1110,55,34,true,C.blue);
txt(s,'Simplified expression: stream through neighbor_index, then read contribution indirectly.',48,298,1170,64,26);
table(s,[['Recorded fact','Gauss–Seidel','Jacobi'],['Kernel (shared correctness check)','PageRank','PageRank'],['Access pattern’s update kind','Read','Read'],['Loop-carried dependency','Yes','No']],48,376,1184,188,[560,312,312],25);
bottom(s,'Code semantics belong to the implementation. Measurements belong to its profiles.');

s=slide('Strategy queries use those code semantics',
`1:45–2:45 (60 seconds). The new extension stores reusable optimization strategies separately from executable implementations. Here is a query we can already answer: which strategies satisfy the recorded conditions for this PageRank gather? Packing and SIMD gather are illegal for the Gauss-Seidel record because its loop-carried dependency conflicts with those strategies’ conditions. The Jacobi record passes the encoded conditions. Software prefetch passes for both. These are query results, not proof that changing the program is correct or profitable. The tool also reports undetermined when required facts are unknown. For packing, manual checks still include whether values remain stable between packing and use, and whether reuse pays for the extra pass. We also record intrinsics and derive their required instruction-set extensions, so profiling can reject incompatible machine or compiler settings. No current production record yet declares that it applies these strategies.`,
['swdb/strategy.py','swdb/db.py','swdb/isa.py','records/strategies/packing.yaml','records/strategies/simd_gather.yaml','records/strategies/software_prefetch.yaml']);
txt(s,'Packing copies gathered values into a contiguous array',48,136,1180,44,30,true,C.blue);
table(s,[['Strategy','Gauss–Seidel','Jacobi'],['Packing','Illegal','Legal'],['SIMD gather','Illegal','Legal'],['Software prefetch','Legal','Legal']],48,205,1184,248,[560,312,312],28);
txt(s,'“Legal” means encoded conditions pass. Manual checks still remain.\nUnknown required facts produce “undetermined.”',48,479,1175,88,27);
bottom(s,'Strategy screening and instruction-set checks work. No measured strategy gains yet.');

s=slide('PageRank scaling changes with input size',
`2:45–4:00 (75 seconds). These are recorded timings for the same Jacobi implementation on two Kronecker inputs. Both runs used the mbit10 Xeon Gold 6326, within one socket, and five trials at each thread count. The chart divides the one-thread median by each multi-thread median. The smaller input reaches about four times speedup and then flattens. The larger input reaches thirteen point three five times at sixteen threads. Their recorded footprints are eight point three three megabytes and five hundred eighty point three five megabytes, compared with a twenty-four mebibyte last-level cache per socket. For the small case, the code’s dynamic chunk size of sixteen thousand three hundred eighty-four gives only four chunks for roughly sixty-five thousand vertices. This helps explain the plateau. We retain measured timing separately from simulated cache misses and inferred bottleneck labels. The result motivates storing profiles per input. It does not by itself establish a memory-latency cause for the larger case.`,
[...pf,'records/machines/mbit10.yaml','apps/gapbs/src/pr_spmv.cc']);
txt(s,'Jacobi PageRank on mbit10: median of 5 trials per thread count',48,128,1184,40,26);
const ch=s.charts.add('line',{position:{left:40,top:184,width:785,height:376},categories:small.timing.map(x=>String(x.threads)),series:[{name:'Scale 16 (65K vertices)',values:small.timing.map(x=>Number((small.timing[0].median_s/x.median_s).toFixed(2))),line:{fill:C.blue,width:4},marker:{symbol:'circle',size:9}},{name:'Scale 22 (4.19M vertices)',values:large.timing.map(x=>Number((large.timing[0].median_s/x.median_s).toFixed(2))),line:{fill:C.light,width:4},marker:{symbol:'square',size:9}}],lineOptions:{smooth:false},hasLegend:true,legend:{position:'bottom',textStyle:{typeface:family,fontSize:22}},xAxis:{title:{text:'Threads',textStyle:{typeface:family,fontSize:22}},textStyle:{typeface:family,fontSize:21},titleTextStyle:{typeface:family,fontSize:22},majorGridlines:null},yAxis:{title:{text:'Speedup vs. 1 thread',textStyle:{typeface:family,fontSize:22}},min:0,max:16,majorUnit:4,numberFormatCode:'0"×"',textStyle:{typeface:family,fontSize:21},majorGridlines:{fill:'#D9E1E8',width:1}},chartFill:C.white,plotAreaFill:C.white});applyPresentationChartFont(ch,{fontFamily:family});
txt(s,'At 16 threads',866,206,350,40,28,true,C.blue);
txt(s,'Scale 16: 3.93×\nScale 22: 13.35×',866,263,355,90,28,true);
txt(s,'Footprint / socket L3\nScale 16: 0.33×\nScale 22: 23.06×',866,382,355,123,26);
bottom(s,'Same implementation, different scaling. Profiles must retain input and machine context.');

s=slide('Next step: apply and evaluate one strategy',
`4:00–5:00 (60 seconds). The completed foundation includes record validation, queries, workload export, profiling, and strategy screening. The current boundary is clear: all records are still drafts, one triangle-counting profile has an incomplete correctness check, and no recorded implementation yet applies a cataloged strategy. I propose making one strategy concrete. We would choose one eligible access pattern, complete the remaining manual checks, implement the change as a derived implementation, and run the kernel’s correctness check. We would then compare that implementation with its own baseline on matched inputs and machine settings, including any added setup work. Packing on Jacobi is a candidate to investigate, not a promised speedup: its amortization may fail. The decision for this meeting is whether this is the right next experiment, and which strategy and implementation should go first.`,
['records/strategies/packing.yaml','swdb/strategy.py','swdb/isa.py','schemas/implementation.schema.json','records/profiles/gapbs-tc-ordered.kron-g22-k16.mbit10.20260922t233432z.yaml']);
txt(s,'Completed',48,139,290,44,30,true,C.blue);txt(s,'Records, queries, profiling, workload export, and strategy screening',338,140,885,80,28);
txt(s,'Current limits',48,254,290,44,30,true,C.blue);txt(s,'No measured strategy applications. One incomplete correctness check.\nAll records retain draft status.',338,254,885,97,28);
txt(s,'Proposed experiment',48,392,1170,44,30,true,C.blue);txt(s,'Choose an eligible strategy and check its remaining conditions.\nImplement it, verify correctness, and measure total cost against its baseline.',48,446,1180,98,28);
bottom(s,'Advisor discussion: which strategy and implementation should we evaluate first?');

s=slide('Backup: complete record inventory','Backup only. Counts are from all YAML records at the stated checkout. The 59 records all retain draft status. Access patterns are nested within implementations, so their count is not added to the record total. All 21 tickets across the initial milestone and strategy extension are marked resolved. Ticket status does not establish research effectiveness.',['records/','.scratch/evolveswdb-2026-09-22/map.md','.scratch/optimization-strategies-2026-09-23/map.md'],true);
table(s,[['Record kind','Count','What it stores'],['Application','1','GAPBS source and version'],['Kernel','6','Computation and correctness check'],['Implementation','8','Code, loops, and 77 access patterns'],['Input','4','Kronecker / uniform, scales 16 / 22'],['Machine','1','mbit10 hardware and CPU flags'],['Profile','32','Measurements for an implementation/input/machine'],['Strategy','5','Target, effects, conditions, reported benefit'],['Intrinsic','2','Instruction wrapper and required ISA']],48,135,1184,423,[260,120,804],23);
bottom(s,'59 records validate. All are draft. 14 initial tickets and 7 extension tickets are resolved.');

s=slide('Backup: application and profile coverage','Backup only. Every implementation has one profile for each of the four pilot inputs, for 32 profiles. Thirty-one are complete. Triangle counting on the larger Kronecker input timed out in its correctness verifier and remains incomplete. Its timing and simulation output must not be treated as correctness-verified performance. Existing implementations come from upstream GAPBS, including Jacobi.',['records/kernels/','records/implementations/','records/inputs/','records/profiles/'],true);
table(s,[['Kernel','Recorded implementations','Profiles'],['PageRank','Gauss–Seidel, Jacobi','8 complete'],['Breadth-first search','Direction-optimizing','4 complete'],['Betweenness centrality','Brandes','4 complete'],['Single-source shortest paths','Delta-stepping','4 complete'],['Connected components','Afforest, Shiloach–Vishkin','8 complete'],['Triangle counting','Ordered','3 complete, 1 incomplete']],48,141,1184,370,[390,510,284],25);
txt(s,'Each implementation uses 4 inputs: Kronecker and uniform random graphs,\neach at scales 16 and 22 with generator parameter k = 16.',48,541,1180,98,26);

s=slide('Backup: implemented database operations','Backup only. YAML is the source of truth and SQLite is a generated query cache. Validation covers schemas, vocabularies and cross-record rules. Adding a record validates it before storing it and rebuilding the cache. Agent-origin additions retain draft status and agent-run provenance. Queries cover access patterns, semantic conditions, implementations and strategies. A workload view adapts stored records to the hardware-side format, but completed integration with a running HW agent is not established here.',['swdb/cli.py','swdb/db.py','swdb/writer.py','swdb/view.py','docs/database.md','docs/adr/0002-yaml-in-git-is-the-master-copy-sqlite-is-generated.md'],true);
table(s,[['Capability','Implemented interface'],['Validate and store records','validate, add, build'],['Search access patterns and semantic facts','find, sql'],['Compare implementations of a kernel','implementations, including --applies'],['Screen strategy targets','strategies --pattern / --loop / --input'],['Export a workload view','view implementation input machine'],['Capture and profile the machine','capture-machine, profile'],['Refresh simulated cache metrics','recompute-cachegrind']],48,142,1184,421,[555,629],24);
bottom(s,'Versioned YAML is the master copy. SQLite is generated for queries.');

s=slide('Backup: profiling and evidence types','Backup only. The profiling pipeline records build provenance, host conditions, correctness checks and stages. Timing uses the application’s trial timer and retains all repetitions, medians, minima, maxima and spreads. Footprints use sizes and formulas. Index-stream features characterize recorded indirect streams and are available in 12 profiles, not all 32. Cachegrind simulates cache behavior at one thread, with kernel-function filtering. Bottleneck labels are inferences from counter-free evidence. The profile stores which stage completed and why other stages did not.',['swdb/profile.py','tools/index_features/','docs/mbit10-profiling.md','records/profiles/'],true);
table(s,[['Evidence','Recorded content','Interpretation'],['Correctness','Verifier outcome and timeout','31 complete profiles'],['Timing','1, 2, 4, 8, 16 threads, 5 trials','Measured application trial time'],['Memory footprint','Array sizes and footprint/L3','Recorded sizes and formulas'],['Index stream','Reuse, sequentiality, degree skew','Features in 12 profiles'],['Cachegrind','Kernel-function cache references/misses','Simulated, single-threaded'],['Bottleneck','Classification with its basis','Inferred, not a counter measurement']],48,148,1184,378,[250,538,396],24);
txt(s,'Profiles retain source/build identity, commands, raw-output locations,\nhost load, thread binding, stage outcomes, and evidence references.',48,558,1180,79,26);

s=slide('Backup: optimization strategies and intrinsics','Backup only. The five strategy records identify changes by target and effect rather than name alone. Parameters such as distance or tile size do not create a new strategy identity. Preconditions return legal, illegal or undetermined, with unencoded obligations retained as manual checks. Benefits in strategy records are reported claims, not measured gains in this project. The intrinsic records cover the prefetch wrapper and an AVX-512 gather wrapper. Intrinsic use derives required ISA extensions for an implementation.',['docs/adr/0004-optimization-strategy-is-a-record-identified-by-its-effect.md','records/strategies/','records/intrinsics/','swdb/strategy.py','swdb/isa.py'],true);
table(s,[['Strategy','Target','Recorded effect'],['Packing','Access pattern','Indirect read becomes a stream, plus a packing pass'],['Software prefetch','Access pattern','Add a non-binding early access'],['SIMD gather','Access pattern','Widen lanes per access'],['Vertex reordering','Input','Reorder indices'],['Loop tiling','Loop','Restructure the loop']],48,141,1184,336,[330,260,594],24);
txt(s,'Intrinsic records: _mm_prefetch and _mm512_i32gather_ps\nStrategy application links and derived ISA checks are implemented.',48,515,1180,89,26);

s=slide('Backup: safeguards and remaining boundaries','Backup only. These distinctions prevent a schema-valid record from being mistaken for a scientifically established result. The database checks references and evidence bases, preserves unknown semantics and enforces ISA requirements during profiling. Workload view generation exists, but this deck does not assert completed hardware-agent integration. The shared-host measurements are from committed profile records. This deck preparation did not rerun them or independently recheck the remote raw files.',['swdb/rules.py','swdb/validate.py','swdb/isa.py','swdb/profile.py','swdb/view.py','.claude/rules/remote_server.md'],true);
table(s,[['Implemented safeguard','Remaining boundary'],['Schema, vocabulary, cross-record checks','Valid structure does not establish a research claim'],['Unknown semantics remain unknown','Strategy screening is not a full correctness proof'],['Derived ISA and compiler/machine checks','No strategy-applied implementation measured yet'],['Correctness status and incomplete profiles','Triangle counting / large Kronecker is incomplete'],['Evidence basis and raw-output references','Simulated cache misses and inferred bottlenecks'],['Workload-view generation','Live HW-agent integration not demonstrated']],48,142,1184,390,[568,616],24);
txt(s,'Measurement context: shared mbit10 host, one socket per run.\nThis update uses committed profile records, not a new measurement campaign.',48,554,1180,83,26);

s=slide('Backup: PageRank timing and setup','Backup only. These are medians in milliseconds, rounded from the profile records. Speedup is the one-thread median divided by the 16-thread median. Each median uses five trials. The two experiments have different graph sizes, so absolute times should not be compared as a speedup. The footprint is recorded in decimal MB, and the cache is 24 MiB = 25,165,824 bytes. The labels parallelism_bound and memory_bound are stored inferences. The small-input implementation uses dynamic scheduling with a chunk size of 16,384. Timing is the application Trial Time, not end-to-end process wall time. Raw records identify build commits and raw-output paths. This deck does not independently revalidate remote files.',[...pf,'apps/gapbs/src/pr_spmv.cc','records/machines/mbit10.yaml'],true);
txt(s,'Intel Xeon Gold 6326, one socket, 24 MiB L3, 5 trials at each thread count',48,130,1184,42,25);
const rows=[['Threads','Scale 16 median (ms)','Scale 22 median (ms)'],...small.timing.map((x,i)=>[String(x.threads),(x.median_s*1000).toFixed(2),(large.timing[i].median_s*1000).toFixed(2)])];
table(s,rows,48,191,1184,294,[260,462,462],25);
txt(s,'Scale 16: 65,536 vertices, recorded footprint 8.33 MB\nScale 22: 4,194,302 vertices, recorded footprint 580.35 MB\nTiming scope: application Trial Time. Raw runs date to 2026-09-22.',48,518,1180,119,26);

await fs.writeFile(path.join(build,'speaker-notes.json'),JSON.stringify(notes,null,2));
await fs.writeFile(path.join(work,'speaker-notes.md'),'# EvolveSWDB weekly update\n\nDate: 2026-09-24 (Eastern Time)\n\nFive-minute talk: slides 1–5. Slides 6–12 are backup.\n\n'+notes.map((n,i)=>`## ${i+1}. ${n.title}\n\n${n.narration}\n\nSources:\n${n.sources.map(x=>'- `'+x+'`').join('\n')}\n`).join('\n'));
const candidate=path.join(build,'candidate.pptx');
await(await PresentationFile.exportPptx(p)).save(candidate);
console.log('Exported candidate');
for(let i=0;i<p.slides.items.length;i++){const s=p.slides.items[i];const png=await p.export({slide:s,format:'png',scale:1});await fs.writeFile(path.join(build,`slide-${String(i+1).padStart(2,'0')}.png`),new Uint8Array(await png.arrayBuffer()));console.log('Rendered',i+1);}
const final=path.join(work,'slides/evolveswdb-week-01-v2.pptx');
await finalizePresentation({workspaceDir:work,candidatePath:candidate,finalPath:final,pythonExecutable:path.join(runtime,'python/bin/python3'),integrityValidatorPath:path.join(skill,'container_tools/inspect_presentation_package_integrity.py'),layoutValidatorPath:path.join(skill,'container_tools/inspect_presentation_layout_geometry.py'),layoutArgs:['--expected-slide-size-emu','12192000,6858000','--validate-bullet-geometry','--validate-heading-fit',...[1,2,3,6,7,8,9,10,11,12].flatMap(n=>['--require-native-table-slide',String(n)])],explicitTotalSlideCount:12,requiredNativeTableOwnerSlides:[1,2,3,6,7,8,9,10,11,12],requiredNativeChartOwnerSlides:[4],materializeLiteralChartWorkbooks:true,fontPolicy:{basis:'design',families:[family]},verifyArtifactToolImport:true,receiptPath:path.join(build,'validation-v2.json')});
console.log('FINAL',final);
