"""`swdb view`: the workload view the HW Ensemble Agent reads.

It joins implementation, kernel, application, input, machine, and (if there is one)
profile into the HW side's workload format (archevolve/hw_ensemble/sparta-sort.input.yaml,
schema_version 0.1). Every key of that format is present with the same nesting; unknown
facts stay explicit (null, or the string "unknown" where that format uses it). Keys the
format lacks are added, never renamed: `code` and `environment` are filled in, and each
pattern gains `pattern_class`, `address_chain`, `semantics_evidence` (the basis of each
semantic value), and `condition` when it runs only sometimes; each array gains
`element_count_formula` and, where it has one, `undirected_alias`. An array used with two
roles in one chain appears once per role.
"""

from swdb import formula
from swdb.cli import Failure
from swdb.machine import llc_bytes
from swdb.store import Store

_MEMORY_OPERATION = {"read": "read", "write": "write", "prefetch": "read"}   # a prefetch only reads a line
_UPDATE_KIND = {"arbitrary": "arbitrary_function"}
_TEXT_FIELDS = {"ordering", "numerical_requirement"}   # the HW format writes these as "unknown" when unknown


def workload_view(records_dir, impl_id, input_id, machine_id, profile_id=None):
    store = Store(records_dir)
    impl = _get(store, impl_id, "implementation")
    inp = _get(store, input_id, "input")
    machine = _get(store, machine_id, "machine")
    kernel = _get(store, impl["kernel"], "kernel")
    app = store.application_of(impl)
    prof = _pick_profile(store, impl_id, input_id, machine_id, profile_id)

    refs = _Refs()
    for record in (app, kernel, impl, inp, machine) + ((prof,) if prof else ()):
        refs.add(record)

    values = {name: fact.get("value") for name, fact in inp["properties"].items()}
    patterns = [_pattern(p, impl, values, refs) for p in impl["access_patterns"]]
    notes = [
        f"Generated by swdb view from records {app['id']}, {kernel['id']}, {impl['id']}, {inp['id']}, {machine['id']}"
        + (f", and profile {prof['id']}." if prof else "; no profile exists yet."),
        "Unknown facts are null (or \"unknown\"); unknown is not false.",
        "element_count is the step's formula evaluated on the input; null means an input property it needs is unknown.",
    ]
    if prof is None:
        notes.append("No profile: counts, metrics, and bottleneck are unknown.")
    elif not prof["complete"]:
        missing = ", ".join(p["part"] for p in prof["parts"] if p["outcome"] not in {"complete", "skipped"})
        notes.append(f"Profile {prof['id']} is incomplete (parts not complete: {missing}).")
        if any(p["part"] == "correctness" and p["outcome"] != "complete" for p in prof["parts"]):
            notes.append("The correctness check did not finish on this input: the implementation is not verified "
                         "here, so treat its measurements as unverified.")
    return {
        "schema_version": "0.1",
        "workload_id": f"{impl['id']}@{inp['id']}@{machine['id']}",
        "benchmark": app["name"],
        "function": f"{impl['function']}()",
        "provenance": refs.entries,
        "code": _code(app, impl),
        "environment": _environment(machine, prof),
        "patterns": patterns,
        "counts": _counts(prof, refs),
        "bottleneck": _bottleneck(prof, refs),
        "metrics": _metrics(prof, refs),
        "notes": notes,
    }


def _get(store, record_id, kind):
    found = store.get(record_id, kind)
    if found is None:
        raise Failure(f"{kind} {record_id!r} does not exist")
    return found


def _pick_profile(store, impl_id, input_id, machine_id, profile_id):
    matching = [r.data for r in store.of_kind("profile")
                if (r.data["implementation"], r.data["input"], r.data["machine"]) == (impl_id, input_id, machine_id)]
    if profile_id:
        for prof in matching:
            if prof["id"] == profile_id:
                return prof
        raise Failure(f"profile {profile_id!r} is not a profile of {impl_id} on {input_id} and {machine_id}")
    if not matching:
        return None
    return max(matching, key=lambda p: (p["complete"], p["environment"]["started"]))


class _Refs:
    """Provenance of every joined record, renamed <record id>:<provenance id> so they stay unique."""

    def __init__(self):
        self.entries = []

    def add(self, record):
        for entry in record["provenance"]:
            self.entries.append({"id": f"{record['id']}:{entry['id']}", "kind": entry["kind"],
                                 "description": entry["description"], "uri": entry.get("uri")})

    @staticmethod
    def of(record, refs):
        return [f"{record['id']}:{ref}" for ref in refs or []]


def _pattern(p, impl, values, refs):
    arrays, seen = [], set()
    for step in p["steps"]:
        a = step["array"]
        if (a["name"], a["role"]) in seen:   # one entry per array and role: a chain may use one array twice
            continue
        seen.add((a["name"], a["role"]))
        entry = {"name": a["name"], "role": a["role"], "element_type": a["element_type"],
                 "element_bytes": a["element_bytes"], "element_count": _evaluate(a.get("element_count"), values),
                 "layout": a["layout"], "element_count_formula": a.get("element_count")}
        if a.get("undirected_alias"):
            entry["undirected_alias"] = a["undirected_alias"]
        arrays.append(entry)
    semantics, evidence = {}, {}
    for name, fact in p["semantics"].items():
        unknown = fact["basis"] == "unknown"
        semantics[name] = ("unknown" if name in _TEXT_FIELDS else None) if unknown else fact["value"]
        evidence[name] = {"basis": fact["basis"], "evidence_refs": _Refs.of(impl, fact.get("evidence_refs")),
                          "note": fact.get("note")}
    chain = []
    for step in p["steps"]:
        link = {"array": step["array"]["name"], "address_shape": step["address_shape"]}
        for attr in ("stride", "index_transform"):
            if attr in step:
                link[attr] = step[attr]
        chain.append(link)
    out = {
        "id": p["id"],
        "expression": p["expression"],
        "memory_operation": _MEMORY_OPERATION.get(p["update_kind"], "read_modify_write"),
        "update": {"kind": _UPDATE_KIND.get(p["update_kind"], p["update_kind"]),
                   "pseudocode": (p.get("update") or {}).get("pseudocode"),
                   "side_effects": (p.get("update") or {}).get("side_effects")},
        "arrays": arrays,
        "semantics": semantics,
        "evidence_refs": _Refs.of(impl, p.get("evidence_refs")),
        "pattern_class": " > ".join(s["address_shape"] for s in p["steps"]) + " : " + p["update_kind"],
        "address_chain": chain,
        "semantics_evidence": evidence,
    }
    if p.get("condition"):
        out["condition"] = p["condition"]
    return out


def _evaluate(text, values):
    if text is None:   # the size depends on the data at run time
        return None
    try:
        return formula.evaluate(text, values)
    except formula.FormulaError as exc:
        raise Failure(str(exc)) from None


def _code(app, impl):
    main = impl["code"][0]
    return {"application": app["id"], "uri": app["source"]["uri"], "commit": app["source"]["commit"],
            "root": main["root"], "file": main["path"], "lines": main.get("lines"), "function": impl["function"],
            "build_command": impl["build"]["command"], "flags": impl["build"]["flags"]}


def _environment(machine, prof):
    env = {"machine": machine["id"], "hostname": machine["hostname"], "cpu_model": machine["cpu"]["model"],
           "sockets": machine["cpu"]["sockets"], "cores_per_socket": machine["cpu"]["cores_per_socket"],
           "llc_bytes_per_socket": llc_bytes(machine), "memory_bytes": machine["memory_bytes"],
           "os_kernel": machine["os"]["kernel"],
           "hardware_counters_available": machine["counters"]["hardware_counters_available"]["value"],
           "compiler": None, "flags": None, "threads": None, "binding": None, "source_commit": None,
           "swdb_commit": None}
    if prof:
        env.update({"compiler": prof["build"]["compiler_version"], "flags": prof["build"]["flags"],
                    "threads": sorted({t["threads"] for t in prof["timing"]}),
                    "binding": prof["environment"]["binding"],
                    "source_commit": prof["build"]["application_commit"], "swdb_commit": prof["build"]["swdb_commit"]})
    return env


def _counts(prof, refs):
    unknown = {"iterations": {"value": None, "scope": "unknown", "evidence_refs": []},
               "repetitions": {"value": None, "meaning": "unknown", "evidence_refs": []}}
    if prof is None:
        return unknown
    counts = {}
    for name, count in prof["counts"].items():
        entry = {"value": count.get("value"), "scope": count["scope"], "basis": count["basis"],
                 "evidence_refs": _Refs.of(prof, count.get("evidence_refs"))}
        if count.get("note"):
            entry["meaning"] = count["note"]
        counts[name] = entry
    counts.setdefault("iterations", unknown["iterations"])
    if "repetitions" not in counts:
        counts["repetitions"] = unknown["repetitions"]
    else:
        counts["repetitions"].setdefault("meaning", "unknown")
    return counts


def _bottleneck(prof, refs):
    if prof is None:
        return {"classification": "unknown", "basis": "unknown", "memory_limit": "unknown", "evidence_refs": []}
    b = prof["bottleneck"]
    return {"classification": b["value"] if b["value"] is not None else "unknown", "basis": b["basis"],
            "memory_limit": b["memory_limit"] if b["memory_limit"] is not None else "unknown",
            "evidence_refs": _Refs.of(prof, b.get("evidence_refs")), "rests_on": b["rests_on"], "note": b.get("note")}


def _metrics(prof, refs):
    if prof is None:
        return []
    found = []
    for m in prof["metrics"]:
        entry = {key: m.get(key) for key in ("name", "value", "unit", "basis", "threads", "array", "scope", "tool")}
        entry["evidence_refs"] = _Refs.of(prof, m.get("evidence_refs"))
        found.append({k: v for k, v in entry.items() if v is not None or k in ("value",)})
    return found
